server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movies-api
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/movies/**
        - id: movies-api
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/series/**    
        - id: persons-api
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/actors/**
        - id: persons-api
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/directors/**    
