server:
  port: 8010

spring:
  application:
    name: mvsc-movies
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3307/db_microservices
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}