server:
  port: 8010

spring:
  application:
    name: mvsc-movies
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}