server:
  port: 8761

spring:
  config:
    import: optional:configserver:http://localhost:8888 

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: localhost:${server.port}/eureka
