GET http://localhost:8010/api/v1/movies
###
GET http://localhost:8010/api/v1/movies/1
###
GET http://localhost:8010/api/v1/movies/title?title=titanic
###
GET http://localhost:8010/api/v1/movies/gender?gender=TERROR
###
POST http://localhost:8010/api/v1/movies
Content-Type: application/json

{
    "title": "Saw",
    "gender": ["TERROR","SUSPENSE"],
    "duration": 30000
}
###
PUT http://localhost:8010/api/v1/movies/3
Content-Type: application/json

{
    "title": "Slenderman",
    "gender": ["TERROR","SUSPENSE", "ACTION"],
    "duration": 12000
}