GET http://localhost:8010/api/v1/series
###
GET http://localhost:8010/api/v1/series/3
###
GET http://localhost:8010/api/v1/series/title?title=swat
###
GET http://localhost:8010/api/v1/series/gender?gender=ACTION
###
POST http://localhost:8010/api/v1/series
Content-Type: application/json

{
    "title": "Swat",
    "gender": ["ACTION", "DRAMA", "SUSPENSE"],
    "seasons": 10,
    "premiereDate": "2012-01-12",
    "actorsId": [1,2]
}
###
PUT http://localhost:8010/api/v1/series/1
Content-Type: application/json

{
    "title": "Braking Bad",
    "gender": ["ACTION", "SCIENCE_FICTION"],
    "acotrsId": [4, 7]
}